-- RZV veritabani yapisi — 2/6: ANAHTARLAR, TEKILLIK, KONTROLLER, BAGLANTILAR
alter table public.aktif_oturumlar add constraint aktif_oturumlar_pkey PRIMARY KEY (user_id);
alter table public.companies add constraint companies_pkey PRIMARY KEY (id);
alter table public.dining_areas add constraint dining_areas_pkey PRIMARY KEY (id);
alter table public.dolu_gun_talepleri add constraint dolu_gun_talepleri_pkey PRIMARY KEY (id);
alter table public.fix_menuler add constraint fix_menuler_pkey PRIMARY KEY (id);
alter table public.katilim_kodlari add constraint katilim_kodlari_pkey PRIMARY KEY (id);
alter table public.kisi_kart_baglantilari add constraint kisi_kart_baglantilari_pkey PRIMARY KEY (id);
alter table public.kisi_kartlari add constraint kisi_kartlari_pkey PRIMARY KEY (id);
alter table public.masa_garson add constraint masa_garson_pkey PRIMARY KEY (id);
alter table public.masa_gruplari add constraint masa_gruplari_pkey PRIMARY KEY (id);
alter table public.masa_olculeri add constraint masa_olculeri_pkey PRIMARY KEY (id);
alter table public.masa_paketleri add constraint masa_paketleri_pkey PRIMARY KEY (id);
alter table public.mesajlar add constraint mesajlar_pkey PRIMARY KEY (id);
alter table public.not_kurallari add constraint not_kurallari_pkey PRIMARY KEY (id);
alter table public.ozel_gece_fiyatlari add constraint ozel_gece_fiyatlari_pkey PRIMARY KEY (id);
alter table public.ozel_geceler add constraint ozel_geceler_pkey PRIMARY KEY (id);
alter table public.personel_hesaplari add constraint personel_hesaplari_pkey PRIMARY KEY (id);
alter table public.platform_yoneticileri add constraint platform_yoneticileri_pkey PRIMARY KEY (user_id);
alter table public.posta_masalari add constraint posta_masalari_pkey PRIMARY KEY (posta_id, table_id);
alter table public.posta_personelleri add constraint posta_personelleri_pkey PRIMARY KEY (posta_id, personel_id);
alter table public.postalar add constraint postalar_pkey PRIMARY KEY (id);
alter table public.reservation_tables add constraint reservation_tables_pkey PRIMARY KEY (id);
alter table public.reservations add constraint reservations_pkey PRIMARY KEY (id);
alter table public.restaurant_photos add constraint restaurant_photos_pkey PRIMARY KEY (id);
alter table public.restaurant_settings add constraint restaurant_settings_pkey PRIMARY KEY (id);
alter table public.restaurant_tables add constraint restaurant_tables_pkey PRIMARY KEY (id);
alter table public.restaurants add constraint restaurants_pkey PRIMARY KEY (id);
alter table public.rezervasyon_etiketleri add constraint rezervasyon_etiketleri_pkey PRIMARY KEY (id);
alter table public.salon_ogeleri add constraint salon_ogeleri_pkey PRIMARY KEY (id);
alter table public.kisi_kartlari add constraint kisi_kartlari_restaurant_id_phone_key UNIQUE (restaurant_id, phone);
alter table public.masa_olculeri add constraint masa_olculeri_restaurant_id_shape_seat_tier_key UNIQUE (restaurant_id, shape, seat_tier);
alter table public.reservation_tables add constraint reservation_tables_reservation_id_table_id_key UNIQUE (reservation_id, table_id);
alter table public.restaurant_settings add constraint restaurant_settings_restaurant_id_key UNIQUE (restaurant_id);
alter table public.restaurants add constraint restaurants_slug_key UNIQUE (slug);
alter table public.masa_olculeri add constraint masa_olculeri_height_cm_check CHECK ((height_cm > (0)::numeric));
alter table public.masa_olculeri add constraint masa_olculeri_seat_tier_check CHECK ((seat_tier = ANY (ARRAY[2, 4, 6, 8])));
alter table public.masa_olculeri add constraint masa_olculeri_shape_check CHECK ((shape = ANY (ARRAY['yuvarlak'::text, 'kare'::text, 'dikdortgen'::text, 'loca'::text])));
alter table public.masa_olculeri add constraint masa_olculeri_width_cm_check CHECK ((width_cm > (0)::numeric));
alter table public.reservations add constraint reservations_party_size_check CHECK ((party_size > 0));
alter table public.reservations add constraint reservations_servis_tipi_check CHECK ((servis_tipi = ANY (ARRAY['fix'::text, 'alakart'::text])));
alter table public.reservations add constraint reservations_source_check CHECK ((source = ANY (ARRAY['rezervasyon'::text, 'kapi'::text, 'online'::text])));
alter table public.reservations add constraint reservations_status_check CHECK ((status = ANY (ARRAY['bekleniyor'::text, 'geldi'::text, 'oturdu'::text, 'tamamlandi'::text, 'gelmedi'::text, 'iptal'::text])));
alter table public.restaurant_settings add constraint restaurant_settings_default_duration_minutes_check CHECK (((default_duration_minutes >= 15) AND (default_duration_minutes <= 600)));
alter table public.restaurant_settings add constraint restaurant_settings_notif_channel_check CHECK ((notif_channel = ANY (ARRAY['kapali'::text, 'sms'::text, 'whatsapp'::text])));
alter table public.restaurant_tables add constraint restaurant_tables_seat_count_check CHECK (((seat_count > 0) AND (seat_count <= 50)));
alter table public.restaurant_tables add constraint restaurant_tables_shape_check CHECK ((shape = ANY (ARRAY['yuvarlak'::text, 'kare'::text, 'dikdortgen'::text, 'loca'::text])));
alter table public.restaurant_tables add constraint restaurant_tables_status_check CHECK ((status = ANY (ARRAY['empty'::text, 'occupied'::text, 'bill_requested'::text, 'reserved'::text, 'kasa_bekliyor'::text, 'toplanacak'::text])));
alter table public.salon_ogeleri add constraint salon_ogeleri_type_check CHECK ((type = ANY (ARRAY['duvar'::text, 'bar'::text, 'kolon'::text, 'servis'::text, 'kapi'::text])));
alter table public.aktif_oturumlar add constraint aktif_oturumlar_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.companies add constraint companies_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id);
alter table public.dining_areas add constraint dining_areas_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.dolu_gun_talepleri add constraint dolu_gun_talepleri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.fix_menuler add constraint fix_menuler_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.katilim_kodlari add constraint katilim_kodlari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.kisi_kart_baglantilari add constraint kisi_kart_baglantilari_kisi_karti_id_fkey FOREIGN KEY (kisi_karti_id) REFERENCES kisi_kartlari(id) ON DELETE CASCADE;
alter table public.kisi_kartlari add constraint kisi_kartlari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.masa_garson add constraint masa_garson_personel_id_fkey FOREIGN KEY (personel_id) REFERENCES personel_hesaplari(id) ON DELETE CASCADE;
alter table public.masa_garson add constraint masa_garson_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.masa_garson add constraint masa_garson_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id) ON DELETE CASCADE;
alter table public.masa_gruplari add constraint masa_gruplari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.masa_olculeri add constraint masa_olculeri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.masa_paketleri add constraint masa_paketleri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.mesajlar add constraint mesajlar_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE;
alter table public.mesajlar add constraint mesajlar_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.not_kurallari add constraint not_kurallari_alan_id_fkey FOREIGN KEY (alan_id) REFERENCES dining_areas(id) ON DELETE CASCADE;
alter table public.not_kurallari add constraint not_kurallari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.ozel_gece_fiyatlari add constraint ozel_gece_fiyatlari_grup_id_fkey FOREIGN KEY (grup_id) REFERENCES masa_gruplari(id) ON DELETE CASCADE;
alter table public.ozel_gece_fiyatlari add constraint ozel_gece_fiyatlari_ozel_gece_id_fkey FOREIGN KEY (ozel_gece_id) REFERENCES ozel_geceler(id) ON DELETE CASCADE;
alter table public.ozel_gece_fiyatlari add constraint ozel_gece_fiyatlari_paket_id_fkey FOREIGN KEY (paket_id) REFERENCES masa_paketleri(id) ON DELETE CASCADE;
alter table public.ozel_geceler add constraint ozel_geceler_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.personel_hesaplari add constraint personel_hesaplari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.personel_hesaplari add constraint personel_hesaplari_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.platform_yoneticileri add constraint platform_yoneticileri_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.posta_masalari add constraint posta_masalari_posta_id_fkey FOREIGN KEY (posta_id) REFERENCES postalar(id) ON DELETE CASCADE;
alter table public.posta_masalari add constraint posta_masalari_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id) ON DELETE CASCADE;
alter table public.posta_personelleri add constraint posta_personelleri_personel_id_fkey FOREIGN KEY (personel_id) REFERENCES personel_hesaplari(id) ON DELETE CASCADE;
alter table public.posta_personelleri add constraint posta_personelleri_posta_id_fkey FOREIGN KEY (posta_id) REFERENCES postalar(id) ON DELETE CASCADE;
alter table public.postalar add constraint postalar_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.reservation_tables add constraint reservation_tables_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE;
alter table public.reservation_tables add constraint reservation_tables_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id);
alter table public.reservations add constraint reservations_alan_hesap_id_fkey FOREIGN KEY (alan_hesap_id) REFERENCES personel_hesaplari(id) ON DELETE SET NULL;
alter table public.reservations add constraint reservations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.reservations add constraint reservations_fix_menu_id_fkey FOREIGN KEY (fix_menu_id) REFERENCES fix_menuler(id) ON DELETE SET NULL;
alter table public.reservations add constraint reservations_geldi_yazan_fkey FOREIGN KEY (geldi_yazan) REFERENCES auth.users(id);
alter table public.reservations add constraint reservations_iptal_eden_fkey FOREIGN KEY (iptal_eden) REFERENCES auth.users(id);
alter table public.reservations add constraint reservations_kisi_karti_id_fkey FOREIGN KEY (kisi_karti_id) REFERENCES kisi_kartlari(id);
alter table public.reservations add constraint reservations_masa_paketi_id_fkey FOREIGN KEY (masa_paketi_id) REFERENCES masa_paketleri(id);
alter table public.reservations add constraint reservations_oturtan_fkey FOREIGN KEY (oturtan) REFERENCES auth.users(id);
alter table public.reservations add constraint reservations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.reservations add constraint reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id);
alter table public.reservations add constraint reservations_tercih_alan_id_fkey FOREIGN KEY (tercih_alan_id) REFERENCES dining_areas(id) ON DELETE SET NULL;
alter table public.restaurant_photos add constraint restaurant_photos_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.restaurant_settings add constraint restaurant_settings_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.restaurant_tables add constraint restaurant_tables_area_id_fkey FOREIGN KEY (area_id) REFERENCES dining_areas(id);
alter table public.restaurant_tables add constraint restaurant_tables_grup_id_fkey FOREIGN KEY (grup_id) REFERENCES masa_gruplari(id) ON DELETE SET NULL;
alter table public.restaurant_tables add constraint restaurant_tables_merged_into_table_id_fkey FOREIGN KEY (merged_into_table_id) REFERENCES restaurant_tables(id);
alter table public.restaurant_tables add constraint restaurant_tables_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.restaurants add constraint restaurants_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.restaurants add constraint restaurants_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id);
alter table public.rezervasyon_etiketleri add constraint rezervasyon_etiketleri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.salon_ogeleri add constraint salon_ogeleri_area_id_fkey FOREIGN KEY (area_id) REFERENCES dining_areas(id);
alter table public.salon_ogeleri add constraint salon_ogeleri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
