-- RZV veritabani yapisi — 2/6: ANAHTARLAR, TEKILLIK, KONTROLLER, BAGLANTILAR
alter table public.aktif_oturumlar add constraint aktif_oturumlar_pkey PRIMARY KEY (user_id);
alter table public.business_expenses add constraint business_expenses_pkey PRIMARY KEY (id);
alter table public.cash_movements add constraint cash_movements_pkey PRIMARY KEY (id);
alter table public.companies add constraint companies_pkey PRIMARY KEY (id);
alter table public.concept_categories add constraint concept_categories_pkey PRIMARY KEY (id);
alter table public.concept_ingredients add constraint concept_ingredients_pkey PRIMARY KEY (id);
alter table public.concept_items add constraint concept_items_pkey PRIMARY KEY (id);
alter table public.concept_recipe_items add constraint concept_recipe_items_pkey PRIMARY KEY (id);
alter table public.concept_templates add constraint concept_templates_pkey PRIMARY KEY (id);
alter table public.day_closures add constraint day_closures_pkey PRIMARY KEY (id);
alter table public.dining_areas add constraint dining_areas_pkey PRIMARY KEY (id);
alter table public.dolu_gun_talepleri add constraint dolu_gun_talepleri_pkey PRIMARY KEY (id);
alter table public.efatura_connections add constraint efatura_connections_pkey PRIMARY KEY (id);
alter table public.fix_menuler add constraint fix_menuler_pkey PRIMARY KEY (id);
alter table public.ingredients add constraint ingredients_pkey PRIMARY KEY (id);
alter table public.inventory_count_items add constraint inventory_count_items_pkey PRIMARY KEY (id);
alter table public.inventory_counts add constraint inventory_counts_pkey PRIMARY KEY (id);
alter table public.katilim_kodlari add constraint katilim_kodlari_pkey PRIMARY KEY (id);
alter table public.kisi_kart_baglantilari add constraint kisi_kart_baglantilari_pkey PRIMARY KEY (id);
alter table public.kisi_kartlari add constraint kisi_kartlari_pkey PRIMARY KEY (id);
alter table public.masa_garson add constraint masa_garson_pkey PRIMARY KEY (id);
alter table public.masa_gruplari add constraint masa_gruplari_pkey PRIMARY KEY (id);
alter table public.masa_olculeri add constraint masa_olculeri_pkey PRIMARY KEY (id);
alter table public.masa_paketleri add constraint masa_paketleri_pkey PRIMARY KEY (id);
alter table public.menu_categories add constraint menu_categories_pkey PRIMARY KEY (id);
alter table public.menu_item_modifier_groups add constraint menu_item_modifier_groups_pkey PRIMARY KEY (id);
alter table public.menu_items add constraint menu_items_pkey PRIMARY KEY (id);
alter table public.mesajlar add constraint mesajlar_pkey PRIMARY KEY (id);
alter table public.modifier_groups add constraint modifier_groups_pkey PRIMARY KEY (id);
alter table public.modifiers add constraint modifiers_pkey PRIMARY KEY (id);
alter table public.not_kurallari add constraint not_kurallari_pkey PRIMARY KEY (id);
alter table public.order_discounts add constraint order_discounts_pkey PRIMARY KEY (id);
alter table public.order_item_modifiers add constraint order_item_modifiers_pkey PRIMARY KEY (id);
alter table public.order_items add constraint order_items_pkey PRIMARY KEY (id);
alter table public.order_payments add constraint order_payments_pkey PRIMARY KEY (id);
alter table public.orders add constraint orders_pkey PRIMARY KEY (id);
alter table public.overtime_consents add constraint overtime_consents_pkey PRIMARY KEY (id);
alter table public.ozel_gece_fiyatlari add constraint ozel_gece_fiyatlari_pkey PRIMARY KEY (id);
alter table public.ozel_geceler add constraint ozel_geceler_pkey PRIMARY KEY (id);
alter table public.payment_providers add constraint payment_providers_pkey PRIMARY KEY (id);
alter table public.personel_hesaplari add constraint personel_hesaplari_pkey PRIMARY KEY (id);
alter table public.platform_yoneticileri add constraint platform_yoneticileri_pkey PRIMARY KEY (user_id);
alter table public.posta_masalari add constraint posta_masalari_pkey PRIMARY KEY (posta_id, table_id);
alter table public.posta_personelleri add constraint posta_personelleri_pkey PRIMARY KEY (posta_id, personel_id);
alter table public.postalar add constraint postalar_pkey PRIMARY KEY (id);
alter table public.product_variants add constraint product_variants_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.public_holidays add constraint public_holidays_pkey PRIMARY KEY (id);
alter table public.purchase_items add constraint purchase_items_pkey PRIMARY KEY (id);
alter table public.purchase_requests add constraint purchase_requests_pkey PRIMARY KEY (id);
alter table public.purchases add constraint purchases_pkey PRIMARY KEY (id);
alter table public.recipe_items add constraint recipe_items_pkey PRIMARY KEY (id);
alter table public.reservation_tables add constraint reservation_tables_pkey PRIMARY KEY (id);
alter table public.reservations add constraint reservations_pkey PRIMARY KEY (id);
alter table public.restaurant_photos add constraint restaurant_photos_pkey PRIMARY KEY (id);
alter table public.restaurant_settings add constraint restaurant_settings_pkey PRIMARY KEY (id);
alter table public.restaurant_tables add constraint restaurant_tables_pkey PRIMARY KEY (id);
alter table public.restaurants add constraint restaurants_pkey PRIMARY KEY (id);
alter table public.rezervasyon_etiketleri add constraint rezervasyon_etiketleri_pkey PRIMARY KEY (id);
alter table public.salon_ogeleri add constraint salon_ogeleri_pkey PRIMARY KEY (id);
alter table public.settlement_receipts add constraint settlement_receipts_pkey PRIMARY KEY (id);
alter table public.staff_leaves add constraint staff_leaves_pkey PRIMARY KEY (id);
alter table public.staff_members add constraint staff_members_pkey PRIMARY KEY (id);
alter table public.staff_shifts add constraint staff_shifts_pkey PRIMARY KEY (id);
alter table public.stations add constraint stations_pkey PRIMARY KEY (id);
alter table public.stock_groups add constraint stock_groups_pkey PRIMARY KEY (id);
alter table public.stock_movements add constraint stock_movements_pkey PRIMARY KEY (id);
alter table public.suppliers add constraint suppliers_pkey PRIMARY KEY (id);
alter table public.table_status_events add constraint table_status_events_pkey PRIMARY KEY (id);
alter table public.valet_entries add constraint valet_entries_pkey PRIMARY KEY (id);
alter table public.concept_recipe_items add constraint concept_recipe_items_item_id_ingredient_id_key UNIQUE (item_id, ingredient_id);
alter table public.concept_templates add constraint concept_templates_name_key UNIQUE (name);
alter table public.day_closures add constraint day_closures_restaurant_id_closure_date_key UNIQUE (restaurant_id, closure_date);
alter table public.inventory_count_items add constraint inventory_count_items_count_id_ingredient_id_key UNIQUE (count_id, ingredient_id);
alter table public.kisi_kartlari add constraint kisi_kartlari_restaurant_id_phone_key UNIQUE (restaurant_id, phone);
alter table public.masa_olculeri add constraint masa_olculeri_restaurant_id_shape_seat_tier_key UNIQUE (restaurant_id, shape, seat_tier);
alter table public.menu_item_modifier_groups add constraint menu_item_modifier_groups_menu_item_id_group_id_key UNIQUE (menu_item_id, group_id);
alter table public.overtime_consents add constraint overtime_consents_staff_id_consent_year_key UNIQUE (staff_id, consent_year);
alter table public.public_holidays add constraint public_holidays_holiday_date_key UNIQUE (holiday_date);
alter table public.recipe_items add constraint recipe_items_menu_item_id_ingredient_id_key UNIQUE (menu_item_id, ingredient_id);
alter table public.reservation_tables add constraint reservation_tables_reservation_id_table_id_key UNIQUE (reservation_id, table_id);
alter table public.restaurant_settings add constraint restaurant_settings_restaurant_id_key UNIQUE (restaurant_id);
alter table public.restaurants add constraint restaurants_slug_key UNIQUE (slug);
alter table public.business_expenses add constraint business_expenses_monthly_amount_check CHECK ((monthly_amount >= (0)::numeric));
alter table public.cash_movements add constraint cash_movements_amount_check CHECK ((amount > (0)::numeric));
alter table public.cash_movements add constraint cash_movements_movement_type_check CHECK ((movement_type = ANY (ARRAY['devir'::text, 'giris'::text, 'cikis'::text])));
alter table public.concept_ingredients add constraint concept_ingredients_unit_check CHECK ((unit = ANY (ARRAY['kg'::text, 'lt'::text, 'adet'::text])));
alter table public.concept_recipe_items add constraint concept_recipe_items_quantity_check CHECK ((quantity > (0)::numeric));
alter table public.efatura_connections add constraint efatura_connections_provider_check CHECK ((provider = ANY (ARRAY['gib'::text, 'entegrator'::text])));
alter table public.efatura_connections add constraint efatura_connections_status_check CHECK ((status = ANY (ARRAY['bagli_degil'::text, 'kuruluyor'::text, 'aktif'::text, 'hata'::text])));
alter table public.ingredients add constraint ingredients_category_check CHECK ((category = ANY (ARRAY['gida'::text, 'sarf'::text])));
alter table public.ingredients add constraint ingredients_current_unit_cost_check CHECK ((current_unit_cost >= (0)::numeric));
alter table public.ingredients add constraint ingredients_diet_class_check CHECK ((diet_class = ANY (ARRAY['bitkisel'::text, 'hayvansal'::text, 'et'::text])));
alter table public.ingredients add constraint ingredients_unit_check CHECK ((unit = ANY (ARRAY['kg'::text, 'lt'::text, 'adet'::text])));
alter table public.ingredients add constraint ingredients_waste_tolerance_percent_check CHECK ((waste_tolerance_percent >= (0)::numeric));
alter table public.inventory_count_items add constraint inventory_count_items_counted_quantity_check CHECK ((counted_quantity >= (0)::numeric));
alter table public.masa_olculeri add constraint masa_olculeri_height_cm_check CHECK ((height_cm > (0)::numeric));
alter table public.masa_olculeri add constraint masa_olculeri_seat_tier_check CHECK ((seat_tier = ANY (ARRAY[2, 4, 6, 8])));
alter table public.masa_olculeri add constraint masa_olculeri_shape_check CHECK ((shape = ANY (ARRAY['yuvarlak'::text, 'kare'::text, 'dikdortgen'::text, 'loca'::text])));
alter table public.masa_olculeri add constraint masa_olculeri_width_cm_check CHECK ((width_cm > (0)::numeric));
alter table public.menu_items add constraint menu_items_sale_price_check CHECK ((sale_price >= (0)::numeric));
alter table public.order_discounts add constraint order_discounts_amount_check CHECK ((amount > (0)::numeric));
alter table public.order_items add constraint order_items_quantity_check CHECK ((quantity > 0));
alter table public.order_items add constraint order_items_status_check CHECK ((status = ANY (ARRAY['active'::text, 'void'::text, 'ikram'::text, 'personel'::text])));
alter table public.order_items add constraint order_items_unit_price_check CHECK ((unit_price >= (0)::numeric));
alter table public.order_payments add constraint order_payments_amount_check CHECK ((amount > (0)::numeric));
alter table public.order_payments add constraint order_payments_method_check CHECK ((method = ANY (ARRAY['nakit'::text, 'kart'::text, 'yemek_karti'::text])));
alter table public.orders add constraint orders_channel_check CHECK ((channel = ANY (ARRAY['dine_in'::text, 'paket'::text, 'yemeksepeti'::text, 'getir'::text, 'trendyol'::text, 'personel'::text])));
alter table public.orders add constraint orders_party_size_check CHECK ((party_size > 0));
alter table public.orders add constraint orders_source_check CHECK (((source IS NULL) OR (source = ANY (ARRAY['kasa'::text, 'qr'::text]))));
alter table public.orders add constraint orders_status_check CHECK ((status = ANY (ARRAY['open'::text, 'pending_cashier'::text, 'closed'::text, 'cancelled'::text, 'transferred'::text])));
alter table public.payment_providers add constraint payment_providers_commission_rate_check CHECK (((commission_rate >= (0)::numeric) AND (commission_rate < (100)::numeric)));
alter table public.payment_providers add constraint payment_providers_method_check CHECK ((method = ANY (ARRAY['kart'::text, 'yemek_karti'::text])));
alter table public.payment_providers add constraint payment_providers_settlement_days_check CHECK ((settlement_days >= 0));
alter table public.product_variants add constraint product_variants_sale_price_check CHECK ((sale_price >= (0)::numeric));
alter table public.profiles add constraint profiles_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'garson'::text, 'sef'::text])));
alter table public.public_holidays add constraint public_holidays_kind_check CHECK ((kind = ANY (ARRAY['resmi'::text, 'dini'::text, 'yas'::text, 'ramazan'::text])));
alter table public.purchase_items add constraint purchase_items_quantity_check CHECK ((quantity > (0)::numeric));
alter table public.purchase_items add constraint purchase_items_unit_price_check CHECK ((unit_price >= (0)::numeric));
alter table public.purchase_requests add constraint purchase_requests_status_check CHECK ((status = ANY (ARRAY['bekliyor'::text, 'onaylandi'::text, 'siparis_verildi'::text, 'reddedildi'::text, 'karsilandi'::text])));
alter table public.purchases add constraint purchases_source_check CHECK ((source = ANY (ARRAY['manuel'::text, 'e_fatura'::text, 'ai_foto'::text])));
alter table public.recipe_items add constraint recipe_items_quantity_check CHECK ((quantity > (0)::numeric));
alter table public.reservations add constraint reservations_party_size_check CHECK ((party_size > 0));
alter table public.reservations add constraint reservations_servis_tipi_check CHECK ((servis_tipi = ANY (ARRAY['fix'::text, 'alakart'::text])));
alter table public.reservations add constraint reservations_source_check CHECK ((source = ANY (ARRAY['rezervasyon'::text, 'kapi'::text, 'online'::text])));
alter table public.reservations add constraint reservations_status_check CHECK ((status = ANY (ARRAY['bekleniyor'::text, 'geldi'::text, 'oturdu'::text, 'tamamlandi'::text, 'gelmedi'::text, 'iptal'::text])));
alter table public.restaurant_settings add constraint restaurant_settings_default_duration_minutes_check CHECK (((default_duration_minutes >= 15) AND (default_duration_minutes <= 600)));
alter table public.restaurant_settings add constraint restaurant_settings_default_menu_design_check CHECK ((default_menu_design = ANY (ARRAY['fotografli'::text, 'listeli'::text])));
alter table public.restaurant_settings add constraint restaurant_settings_evening_start_hour_check CHECK (((evening_start_hour >= 0) AND (evening_start_hour <= 23)));
alter table public.restaurant_settings add constraint restaurant_settings_kitchen_tip_percent_check CHECK (((kitchen_tip_percent >= (0)::numeric) AND (kitchen_tip_percent <= (100)::numeric)));
alter table public.restaurant_settings add constraint restaurant_settings_notif_channel_check CHECK ((notif_channel = ANY (ARRAY['kapali'::text, 'sms'::text, 'whatsapp'::text])));
alter table public.restaurant_settings add constraint restaurant_settings_table_flow_mode_check CHECK ((table_flow_mode = ANY (ARRAY['basit'::text, 'garson_takipli'::text, 'karsilamali'::text])));
alter table public.restaurant_tables add constraint restaurant_tables_seat_count_check CHECK (((seat_count > 0) AND (seat_count <= 50)));
alter table public.restaurant_tables add constraint restaurant_tables_shape_check CHECK ((shape = ANY (ARRAY['yuvarlak'::text, 'kare'::text, 'dikdortgen'::text, 'loca'::text])));
alter table public.restaurant_tables add constraint restaurant_tables_status_check CHECK ((status = ANY (ARRAY['empty'::text, 'occupied'::text, 'bill_requested'::text, 'reserved'::text, 'kasa_bekliyor'::text, 'toplanacak'::text])));
alter table public.salon_ogeleri add constraint salon_ogeleri_type_check CHECK ((type = ANY (ARRAY['duvar'::text, 'bar'::text, 'kolon'::text, 'servis'::text, 'kapi'::text])));
alter table public.settlement_receipts add constraint settlement_receipts_amount_check CHECK ((amount > (0)::numeric));
alter table public.staff_leaves add constraint staff_leaves_check CHECK ((end_date >= start_date));
alter table public.staff_leaves add constraint staff_leaves_leave_type_check CHECK ((leave_type = ANY (ARRAY['yillik'::text, 'ucretsiz'::text, 'raporlu'::text, 'mazeret'::text])));
alter table public.staff_members add constraint staff_members_role_check CHECK ((role = ANY (ARRAY['garson'::text, 'mutfak'::text, 'bar'::text, 'kasa'::text, 'sef'::text, 'yonetici'::text, 'vale'::text, 'karsilama'::text, 'bulasik'::text])));
alter table public.stock_movements add constraint stock_movements_movement_type_check CHECK ((movement_type = ANY (ARRAY['purchase'::text, 'consumption'::text, 'waste'::text, 'count_adjustment'::text])));
alter table public.stock_movements add constraint stock_movements_source_type_check CHECK ((source_type = ANY (ARRAY['order'::text, 'purchase'::text, 'count'::text, 'manual'::text])));
alter table public.suppliers add constraint suppliers_delivery_frequency_check CHECK ((delivery_frequency = ANY (ARRAY['daily'::text, 'weekly'::text, 'custom'::text])));
alter table public.valet_entries add constraint valet_entries_status_check CHECK ((status = ANY (ARRAY['bekliyor'::text, 'cagrildi'::text, 'teslim_edildi'::text])));
alter table public.aktif_oturumlar add constraint aktif_oturumlar_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.business_expenses add constraint business_expenses_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.cash_movements add constraint cash_movements_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.companies add constraint companies_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id);
alter table public.concept_categories add constraint concept_categories_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES concept_templates(id) ON DELETE CASCADE;
alter table public.concept_ingredients add constraint concept_ingredients_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES concept_templates(id) ON DELETE CASCADE;
alter table public.concept_items add constraint concept_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES concept_categories(id) ON DELETE CASCADE;
alter table public.concept_items add constraint concept_items_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES concept_templates(id) ON DELETE CASCADE;
alter table public.concept_recipe_items add constraint concept_recipe_items_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES concept_ingredients(id) ON DELETE CASCADE;
alter table public.concept_recipe_items add constraint concept_recipe_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES concept_items(id) ON DELETE CASCADE;
alter table public.day_closures add constraint day_closures_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.dining_areas add constraint dining_areas_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.dolu_gun_talepleri add constraint dolu_gun_talepleri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.efatura_connections add constraint efatura_connections_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.fix_menuler add constraint fix_menuler_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.ingredients add constraint ingredients_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.ingredients add constraint ingredients_stock_group_id_fkey FOREIGN KEY (stock_group_id) REFERENCES stock_groups(id);
alter table public.ingredients add constraint ingredients_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
alter table public.inventory_count_items add constraint inventory_count_items_count_id_fkey FOREIGN KEY (count_id) REFERENCES inventory_counts(id);
alter table public.inventory_count_items add constraint inventory_count_items_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
alter table public.inventory_count_items add constraint inventory_count_items_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.inventory_counts add constraint inventory_counts_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.katilim_kodlari add constraint katilim_kodlari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.kisi_kart_baglantilari add constraint kisi_kart_baglantilari_kisi_karti_id_fkey FOREIGN KEY (kisi_karti_id) REFERENCES kisi_kartlari(id) ON DELETE CASCADE;
alter table public.kisi_kartlari add constraint kisi_kartlari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.masa_garson add constraint masa_garson_personel_id_fkey FOREIGN KEY (personel_id) REFERENCES personel_hesaplari(id) ON DELETE CASCADE;
alter table public.masa_garson add constraint masa_garson_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.masa_garson add constraint masa_garson_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff_members(id) ON DELETE CASCADE;
alter table public.masa_garson add constraint masa_garson_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id) ON DELETE CASCADE;
alter table public.masa_gruplari add constraint masa_gruplari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.masa_olculeri add constraint masa_olculeri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.masa_paketleri add constraint masa_paketleri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.menu_categories add constraint menu_categories_default_station_id_fkey FOREIGN KEY (default_station_id) REFERENCES stations(id) ON DELETE SET NULL;
alter table public.menu_categories add constraint menu_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES menu_categories(id);
alter table public.menu_categories add constraint menu_categories_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.menu_item_modifier_groups add constraint menu_item_modifier_groups_group_id_fkey FOREIGN KEY (group_id) REFERENCES modifier_groups(id);
alter table public.menu_item_modifier_groups add constraint menu_item_modifier_groups_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES menu_items(id);
alter table public.menu_item_modifier_groups add constraint menu_item_modifier_groups_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.menu_items add constraint menu_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES menu_categories(id);
alter table public.menu_items add constraint menu_items_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.menu_items add constraint menu_items_station_override_id_fkey FOREIGN KEY (station_override_id) REFERENCES stations(id) ON DELETE SET NULL;
alter table public.mesajlar add constraint mesajlar_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE;
alter table public.mesajlar add constraint mesajlar_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.modifier_groups add constraint modifier_groups_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.modifiers add constraint modifiers_group_id_fkey FOREIGN KEY (group_id) REFERENCES modifier_groups(id);
alter table public.modifiers add constraint modifiers_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.not_kurallari add constraint not_kurallari_alan_id_fkey FOREIGN KEY (alan_id) REFERENCES dining_areas(id) ON DELETE CASCADE;
alter table public.not_kurallari add constraint not_kurallari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.order_discounts add constraint order_discounts_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
alter table public.order_discounts add constraint order_discounts_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id);
alter table public.order_discounts add constraint order_discounts_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.order_item_modifiers add constraint order_item_modifiers_modifier_id_fkey FOREIGN KEY (modifier_id) REFERENCES modifiers(id);
alter table public.order_item_modifiers add constraint order_item_modifiers_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE;
alter table public.order_item_modifiers add constraint order_item_modifiers_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.order_items add constraint order_items_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES menu_items(id);
alter table public.order_items add constraint order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
alter table public.order_items add constraint order_items_original_table_id_fkey FOREIGN KEY (original_table_id) REFERENCES restaurant_tables(id);
alter table public.order_items add constraint order_items_prepared_by_staff_id_fkey FOREIGN KEY (prepared_by_staff_id) REFERENCES staff_members(id);
alter table public.order_items add constraint order_items_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.order_items add constraint order_items_sent_by_staff_id_fkey FOREIGN KEY (sent_by_staff_id) REFERENCES staff_members(id);
alter table public.order_items add constraint order_items_staff_meal_for_id_fkey FOREIGN KEY (staff_meal_for_id) REFERENCES staff_members(id);
alter table public.order_items add constraint order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id);
alter table public.order_items add constraint order_items_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES profiles(id);
alter table public.order_payments add constraint order_payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
alter table public.order_payments add constraint order_payments_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES payment_providers(id);
alter table public.order_payments add constraint order_payments_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.orders add constraint orders_cashier_confirmed_by_fkey FOREIGN KEY (cashier_confirmed_by) REFERENCES staff_members(id);
alter table public.orders add constraint orders_closed_by_staff_id_fkey FOREIGN KEY (closed_by_staff_id) REFERENCES staff_members(id);
alter table public.orders add constraint orders_payment_collected_by_fkey FOREIGN KEY (payment_collected_by) REFERENCES staff_members(id);
alter table public.orders add constraint orders_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.orders add constraint orders_split_from_order_id_fkey FOREIGN KEY (split_from_order_id) REFERENCES orders(id);
alter table public.orders add constraint orders_split_from_table_id_fkey FOREIGN KEY (split_from_table_id) REFERENCES restaurant_tables(id);
alter table public.orders add constraint orders_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id);
alter table public.overtime_consents add constraint overtime_consents_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.overtime_consents add constraint overtime_consents_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff_members(id);
alter table public.ozel_gece_fiyatlari add constraint ozel_gece_fiyatlari_grup_id_fkey FOREIGN KEY (grup_id) REFERENCES masa_gruplari(id) ON DELETE CASCADE;
alter table public.ozel_gece_fiyatlari add constraint ozel_gece_fiyatlari_ozel_gece_id_fkey FOREIGN KEY (ozel_gece_id) REFERENCES ozel_geceler(id) ON DELETE CASCADE;
alter table public.ozel_gece_fiyatlari add constraint ozel_gece_fiyatlari_paket_id_fkey FOREIGN KEY (paket_id) REFERENCES masa_paketleri(id) ON DELETE CASCADE;
alter table public.ozel_geceler add constraint ozel_geceler_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.payment_providers add constraint payment_providers_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.personel_hesaplari add constraint personel_hesaplari_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.personel_hesaplari add constraint personel_hesaplari_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff_members(id) ON DELETE SET NULL;
alter table public.personel_hesaplari add constraint personel_hesaplari_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.platform_yoneticileri add constraint platform_yoneticileri_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.posta_masalari add constraint posta_masalari_posta_id_fkey FOREIGN KEY (posta_id) REFERENCES postalar(id) ON DELETE CASCADE;
alter table public.posta_masalari add constraint posta_masalari_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id) ON DELETE CASCADE;
alter table public.posta_personelleri add constraint posta_personelleri_personel_id_fkey FOREIGN KEY (personel_id) REFERENCES personel_hesaplari(id) ON DELETE CASCADE;
alter table public.posta_personelleri add constraint posta_personelleri_posta_id_fkey FOREIGN KEY (posta_id) REFERENCES postalar(id) ON DELETE CASCADE;
alter table public.postalar add constraint postalar_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.product_variants add constraint product_variants_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES menu_items(id);
alter table public.product_variants add constraint product_variants_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.purchase_items add constraint purchase_items_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
alter table public.purchase_items add constraint purchase_items_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES purchases(id);
alter table public.purchase_items add constraint purchase_items_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.purchase_requests add constraint purchase_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES profiles(id);
alter table public.purchase_requests add constraint purchase_requests_approved_by_staff_id_fkey FOREIGN KEY (approved_by_staff_id) REFERENCES staff_members(id);
alter table public.purchase_requests add constraint purchase_requests_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
alter table public.purchase_requests add constraint purchase_requests_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES purchases(id);
alter table public.purchase_requests add constraint purchase_requests_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.purchase_requests add constraint purchase_requests_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
alter table public.purchases add constraint purchases_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.purchases add constraint purchases_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
alter table public.recipe_items add constraint recipe_items_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
alter table public.recipe_items add constraint recipe_items_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES menu_items(id);
alter table public.recipe_items add constraint recipe_items_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.reservation_tables add constraint reservation_tables_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE;
alter table public.reservation_tables add constraint reservation_tables_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id);
alter table public.reservations add constraint reservations_alan_hesap_id_fkey FOREIGN KEY (alan_hesap_id) REFERENCES personel_hesaplari(id) ON DELETE SET NULL;
alter table public.reservations add constraint reservations_alan_personel_id_fkey FOREIGN KEY (alan_personel_id) REFERENCES staff_members(id) ON DELETE SET NULL;
alter table public.reservations add constraint reservations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.reservations add constraint reservations_fix_menu_id_fkey FOREIGN KEY (fix_menu_id) REFERENCES fix_menuler(id) ON DELETE SET NULL;
alter table public.reservations add constraint reservations_geldi_yazan_fkey FOREIGN KEY (geldi_yazan) REFERENCES auth.users(id);
alter table public.reservations add constraint reservations_iptal_eden_fkey FOREIGN KEY (iptal_eden) REFERENCES auth.users(id);
alter table public.reservations add constraint reservations_kisi_karti_id_fkey FOREIGN KEY (kisi_karti_id) REFERENCES kisi_kartlari(id);
alter table public.reservations add constraint reservations_masa_paketi_id_fkey FOREIGN KEY (masa_paketi_id) REFERENCES masa_paketleri(id);
alter table public.reservations add constraint reservations_oturtan_fkey FOREIGN KEY (oturtan) REFERENCES auth.users(id);
alter table public.reservations add constraint reservations_pr_id_fkey FOREIGN KEY (pr_id) REFERENCES staff_members(id) ON DELETE SET NULL;
alter table public.reservations add constraint reservations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.reservations add constraint reservations_seated_order_id_fkey FOREIGN KEY (seated_order_id) REFERENCES orders(id);
alter table public.reservations add constraint reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id);
alter table public.reservations add constraint reservations_tercih_alan_id_fkey FOREIGN KEY (tercih_alan_id) REFERENCES dining_areas(id) ON DELETE SET NULL;
alter table public.restaurant_photos add constraint restaurant_photos_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.restaurant_settings add constraint restaurant_settings_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.restaurant_tables add constraint restaurant_tables_area_id_fkey FOREIGN KEY (area_id) REFERENCES dining_areas(id);
alter table public.restaurant_tables add constraint restaurant_tables_assigned_staff_id_fkey FOREIGN KEY (assigned_staff_id) REFERENCES staff_members(id);
alter table public.restaurant_tables add constraint restaurant_tables_grup_id_fkey FOREIGN KEY (grup_id) REFERENCES masa_gruplari(id) ON DELETE SET NULL;
alter table public.restaurant_tables add constraint restaurant_tables_merged_into_table_id_fkey FOREIGN KEY (merged_into_table_id) REFERENCES restaurant_tables(id);
alter table public.restaurant_tables add constraint restaurant_tables_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.restaurants add constraint restaurants_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.restaurants add constraint restaurants_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id);
alter table public.rezervasyon_etiketleri add constraint rezervasyon_etiketleri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
alter table public.salon_ogeleri add constraint salon_ogeleri_area_id_fkey FOREIGN KEY (area_id) REFERENCES dining_areas(id);
alter table public.salon_ogeleri add constraint salon_ogeleri_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.settlement_receipts add constraint settlement_receipts_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES payment_providers(id);
alter table public.settlement_receipts add constraint settlement_receipts_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.staff_leaves add constraint staff_leaves_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.staff_leaves add constraint staff_leaves_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff_members(id);
alter table public.staff_members add constraint staff_members_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.staff_shifts add constraint staff_shifts_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.staff_shifts add constraint staff_shifts_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff_members(id);
alter table public.stations add constraint stations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.stock_groups add constraint stock_groups_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.stock_movements add constraint stock_movements_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
alter table public.stock_movements add constraint stock_movements_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.suppliers add constraint suppliers_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.table_status_events add constraint table_status_events_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
alter table public.table_status_events add constraint table_status_events_table_id_fkey FOREIGN KEY (table_id) REFERENCES restaurant_tables(id);
alter table public.valet_entries add constraint valet_entries_matched_table_id_fkey FOREIGN KEY (matched_table_id) REFERENCES restaurant_tables(id);
alter table public.valet_entries add constraint valet_entries_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
