-- RZV veritabani yapisi — 3/6: INDEKSLER
CREATE INDEX idx_business_expenses_restaurant ON public.business_expenses USING btree (restaurant_id);
CREATE INDEX idx_cash_movements_occurred ON public.cash_movements USING btree (occurred_at);
CREATE INDEX idx_cash_movements_restaurant ON public.cash_movements USING btree (restaurant_id);
CREATE INDEX idx_concept_categories_concept ON public.concept_categories USING btree (concept_id);
CREATE INDEX idx_concept_ingredients_concept ON public.concept_ingredients USING btree (concept_id);
CREATE INDEX idx_concept_items_category ON public.concept_items USING btree (category_id);
CREATE INDEX idx_concept_items_concept ON public.concept_items USING btree (concept_id);
CREATE INDEX idx_concept_recipe_items_item ON public.concept_recipe_items USING btree (item_id);
CREATE INDEX idx_day_closures_restaurant ON public.day_closures USING btree (restaurant_id);
CREATE INDEX idx_dining_areas_restaurant ON public.dining_areas USING btree (restaurant_id);
CREATE INDEX idx_dolu_gun_talepleri_restoran ON public.dolu_gun_talepleri USING btree (restaurant_id, gun);
CREATE INDEX idx_efatura_connections_restaurant ON public.efatura_connections USING btree (restaurant_id);
CREATE INDEX idx_fix_menuler_restoran ON public.fix_menuler USING btree (restaurant_id);
CREATE INDEX idx_ingredients_restaurant ON public.ingredients USING btree (restaurant_id);
CREATE INDEX idx_inventory_count_items_count ON public.inventory_count_items USING btree (count_id);
CREATE INDEX idx_inventory_count_items_restaurant ON public.inventory_count_items USING btree (restaurant_id);
CREATE INDEX idx_inventory_counts_restaurant ON public.inventory_counts USING btree (restaurant_id);
CREATE INDEX idx_katilim_restoran ON public.katilim_kodlari USING btree (restaurant_id);
CREATE UNIQUE INDEX uq_katilim_kodu ON public.katilim_kodlari USING btree (kod);
CREATE UNIQUE INDEX uq_katilim_rol ON public.katilim_kodlari USING btree (restaurant_id, rol);
CREATE INDEX idx_kisi_kart_baglantilari_kart ON public.kisi_kart_baglantilari USING btree (kisi_karti_id);
CREATE INDEX idx_kisi_kartlari_restaurant ON public.kisi_kartlari USING btree (restaurant_id);
CREATE INDEX idx_masa_garson_restoran ON public.masa_garson USING btree (restaurant_id, gun);
CREATE UNIQUE INDEX uq_masa_garson_gun ON public.masa_garson USING btree (table_id, gun);
CREATE INDEX idx_masa_gruplari_restoran ON public.masa_gruplari USING btree (restaurant_id);
CREATE INDEX idx_masa_olculeri_restaurant ON public.masa_olculeri USING btree (restaurant_id);
CREATE INDEX idx_masa_paketleri_restoran ON public.masa_paketleri USING btree (restaurant_id);
CREATE INDEX idx_menu_categories_parent ON public.menu_categories USING btree (parent_id);
CREATE INDEX idx_menu_categories_restaurant ON public.menu_categories USING btree (restaurant_id);
CREATE INDEX idx_mimg_item ON public.menu_item_modifier_groups USING btree (menu_item_id);
CREATE INDEX idx_mimg_restaurant ON public.menu_item_modifier_groups USING btree (restaurant_id);
CREATE INDEX idx_menu_items_category ON public.menu_items USING btree (category_id);
CREATE INDEX idx_menu_items_restaurant ON public.menu_items USING btree (restaurant_id);
CREATE INDEX mesajlar_kuyruk_idx ON public.mesajlar USING btree (restaurant_id, durum, planlanan_zaman);
CREATE INDEX mesajlar_rezervasyon_idx ON public.mesajlar USING btree (reservation_id);
CREATE INDEX idx_modifier_groups_restaurant ON public.modifier_groups USING btree (restaurant_id);
CREATE INDEX idx_modifiers_group ON public.modifiers USING btree (group_id);
CREATE INDEX idx_modifiers_restaurant ON public.modifiers USING btree (restaurant_id);
CREATE INDEX idx_not_kurallari_restoran ON public.not_kurallari USING btree (restaurant_id);
CREATE INDEX idx_order_discounts_order ON public.order_discounts USING btree (order_id);
CREATE INDEX idx_order_discounts_restaurant ON public.order_discounts USING btree (restaurant_id);
CREATE INDEX idx_order_item_modifiers_item ON public.order_item_modifiers USING btree (order_item_id);
CREATE INDEX idx_order_item_modifiers_restaurant ON public.order_item_modifiers USING btree (restaurant_id);
CREATE INDEX idx_order_items_needs_approval ON public.order_items USING btree (restaurant_id, order_id) WHERE needs_approval;
CREATE INDEX idx_order_items_order ON public.order_items USING btree (order_id);
CREATE INDEX idx_order_items_restaurant ON public.order_items USING btree (restaurant_id);
CREATE INDEX idx_order_items_staff_meal ON public.order_items USING btree (staff_meal_for_id);
CREATE INDEX idx_order_payments_order ON public.order_payments USING btree (order_id);
CREATE INDEX idx_order_payments_paid_at ON public.order_payments USING btree (paid_at);
CREATE INDEX idx_order_payments_provider ON public.order_payments USING btree (provider_id);
CREATE INDEX idx_order_payments_restaurant ON public.order_payments USING btree (restaurant_id);
CREATE UNIQUE INDEX idx_orders_one_open_per_table ON public.orders USING btree (table_id) WHERE (status = 'open'::text);
CREATE INDEX idx_orders_restaurant ON public.orders USING btree (restaurant_id);
CREATE INDEX idx_orders_split_from_table ON public.orders USING btree (split_from_table_id) WHERE (status = 'open'::text);
CREATE INDEX idx_orders_status ON public.orders USING btree (status);
CREATE INDEX idx_orders_table ON public.orders USING btree (table_id);
CREATE INDEX idx_overtime_consents_restaurant ON public.overtime_consents USING btree (restaurant_id);
CREATE INDEX idx_ozel_gece_fiyat ON public.ozel_gece_fiyatlari USING btree (ozel_gece_id);
CREATE INDEX idx_ozel_geceler_restoran ON public.ozel_geceler USING btree (restaurant_id, gun);
CREATE INDEX idx_payment_providers_restaurant ON public.payment_providers USING btree (restaurant_id);
CREATE UNIQUE INDEX uq_payment_providers_default ON public.payment_providers USING btree (restaurant_id, method) WHERE (is_default AND (deleted_at IS NULL));
CREATE INDEX idx_personel_hesap_restoran ON public.personel_hesaplari USING btree (restaurant_id, durum);
CREATE UNIQUE INDEX uq_personel_hesap_rol ON public.personel_hesaplari USING btree (user_id, restaurant_id, rol) WHERE (test_hesabi = false);
CREATE UNIQUE INDEX uq_posta_masasi ON public.posta_masalari USING btree (table_id);
CREATE INDEX posta_personelleri_personel_idx ON public.posta_personelleri USING btree (personel_id);
CREATE INDEX idx_postalar_restoran ON public.postalar USING btree (restaurant_id);
CREATE INDEX idx_product_variants_item ON public.product_variants USING btree (menu_item_id);
CREATE INDEX idx_product_variants_restaurant ON public.product_variants USING btree (restaurant_id);
CREATE INDEX idx_profiles_restaurant ON public.profiles USING btree (restaurant_id);
CREATE INDEX idx_purchase_items_purchase ON public.purchase_items USING btree (purchase_id);
CREATE INDEX idx_purchase_items_restaurant ON public.purchase_items USING btree (restaurant_id);
CREATE INDEX idx_purchase_requests_restaurant ON public.purchase_requests USING btree (restaurant_id);
CREATE INDEX idx_purchase_requests_status ON public.purchase_requests USING btree (status);
CREATE INDEX idx_purchases_restaurant ON public.purchases USING btree (restaurant_id);
CREATE INDEX idx_recipe_items_menu_item ON public.recipe_items USING btree (menu_item_id);
CREATE INDEX idx_recipe_items_restaurant ON public.recipe_items USING btree (restaurant_id);
CREATE INDEX idx_reservation_tables_reservation ON public.reservation_tables USING btree (reservation_id);
CREATE INDEX idx_reservation_tables_table ON public.reservation_tables USING btree (table_id);
CREATE INDEX idx_reservations_alan_hesap ON public.reservations USING btree (alan_hesap_id);
CREATE INDEX idx_reservations_anonymized ON public.reservations USING btree (anonymized_at);
CREATE INDEX idx_reservations_kisi_karti ON public.reservations USING btree (kisi_karti_id);
CREATE INDEX idx_reservations_reserved_at ON public.reservations USING btree (reserved_at);
CREATE INDEX idx_reservations_restaurant ON public.reservations USING btree (restaurant_id);
CREATE INDEX idx_rez_pr ON public.reservations USING btree (pr_id) WHERE (pr_id IS NOT NULL);
CREATE INDEX reservations_bekleme_idx ON public.reservations USING btree (restaurant_id, bekleme) WHERE (bekleme = true);
CREATE INDEX reservations_kisi_karti_tutar_idx ON public.reservations USING btree (kisi_karti_id) WHERE ((hesap_tutari IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX reservations_yedek_idx ON public.reservations USING btree (restaurant_id, yedek, reserved_at) WHERE (yedek AND (deleted_at IS NULL));
CREATE INDEX restaurant_photos_restaurant_idx ON public.restaurant_photos USING btree (restaurant_id, sira);
CREATE INDEX idx_restaurant_settings_restaurant ON public.restaurant_settings USING btree (restaurant_id);
CREATE INDEX idx_restaurant_tables_restaurant ON public.restaurant_tables USING btree (restaurant_id);
CREATE INDEX restaurant_tables_stok_idx ON public.restaurant_tables USING btree (restaurant_id, stok_gun) WHERE stok;
CREATE INDEX idx_restaurants_owner_user ON public.restaurants USING btree (owner_user_id);
CREATE UNIQUE INDEX uq_restoran_katilim_kodu ON public.restaurants USING btree (katilim_kodu) WHERE (katilim_kodu IS NOT NULL);
CREATE INDEX idx_rez_etiket_restoran ON public.rezervasyon_etiketleri USING btree (restaurant_id);
CREATE INDEX idx_salon_ogeleri_area ON public.salon_ogeleri USING btree (area_id);
CREATE INDEX idx_salon_ogeleri_restaurant ON public.salon_ogeleri USING btree (restaurant_id);
CREATE INDEX idx_settlement_receipts_provider ON public.settlement_receipts USING btree (provider_id);
CREATE INDEX idx_settlement_receipts_restaurant ON public.settlement_receipts USING btree (restaurant_id);
CREATE INDEX idx_staff_leaves_restaurant ON public.staff_leaves USING btree (restaurant_id);
CREATE INDEX idx_staff_leaves_staff ON public.staff_leaves USING btree (staff_id);
CREATE INDEX idx_staff_members_restaurant ON public.staff_members USING btree (restaurant_id);
CREATE INDEX idx_staff_shifts_restaurant ON public.staff_shifts USING btree (restaurant_id);
CREATE INDEX idx_staff_shifts_staff ON public.staff_shifts USING btree (staff_id);
CREATE UNIQUE INDEX uniq_staff_shifts_open ON public.staff_shifts USING btree (staff_id) WHERE (ended_at IS NULL);
CREATE INDEX idx_stations_restaurant ON public.stations USING btree (restaurant_id);
CREATE INDEX idx_stock_groups_restaurant ON public.stock_groups USING btree (restaurant_id);
CREATE INDEX idx_stock_movements_ingredient ON public.stock_movements USING btree (ingredient_id);
CREATE INDEX idx_stock_movements_occurred ON public.stock_movements USING btree (occurred_at);
CREATE INDEX idx_stock_movements_restaurant ON public.stock_movements USING btree (restaurant_id);
CREATE INDEX idx_suppliers_restaurant ON public.suppliers USING btree (restaurant_id);
CREATE INDEX idx_table_status_events_restaurant ON public.table_status_events USING btree (restaurant_id, changed_at);
CREATE INDEX idx_table_status_events_table ON public.table_status_events USING btree (table_id, changed_at);
CREATE INDEX idx_valet_entries_restaurant ON public.valet_entries USING btree (restaurant_id, status, parked_at);
