-- RZV veritabani yapisi — 3/6: INDEKSLER
CREATE INDEX idx_dining_areas_restaurant ON public.dining_areas USING btree (restaurant_id);
CREATE INDEX idx_dolu_gun_talepleri_restoran ON public.dolu_gun_talepleri USING btree (restaurant_id, gun);
CREATE INDEX idx_fix_menuler_restoran ON public.fix_menuler USING btree (restaurant_id);
CREATE INDEX idx_katilim_restoran ON public.katilim_kodlari USING btree (restaurant_id);
CREATE UNIQUE INDEX uq_katilim_kodu ON public.katilim_kodlari USING btree (kod);
CREATE UNIQUE INDEX uq_katilim_rol ON public.katilim_kodlari USING btree (restaurant_id, rol);
CREATE INDEX idx_kisi_kart_baglantilari_kart ON public.kisi_kart_baglantilari USING btree (kisi_karti_id);
CREATE INDEX idx_kisi_kartlari_restaurant ON public.kisi_kartlari USING btree (restaurant_id);
CREATE INDEX idx_masa_garson_restoran ON public.masa_garson USING btree (restaurant_id, gun);
CREATE UNIQUE INDEX uq_masa_garson_gun ON public.masa_garson USING btree (table_id, gun);
CREATE INDEX idx_masa_gruplari_restoran ON public.masa_gruplari USING btree (restaurant_id);
CREATE INDEX idx_masa_olculeri_restaurant ON public.masa_olculeri USING btree (restaurant_id);
CREATE INDEX idx_masa_paketleri_restoran ON public.masa_paketleri USING btree (restaurant_id);
CREATE INDEX mesajlar_kuyruk_idx ON public.mesajlar USING btree (restaurant_id, durum, planlanan_zaman);
CREATE INDEX mesajlar_rezervasyon_idx ON public.mesajlar USING btree (reservation_id);
CREATE INDEX idx_not_kurallari_restoran ON public.not_kurallari USING btree (restaurant_id);
CREATE INDEX idx_ozel_gece_fiyat ON public.ozel_gece_fiyatlari USING btree (ozel_gece_id);
CREATE INDEX idx_ozel_geceler_restoran ON public.ozel_geceler USING btree (restaurant_id, gun);
CREATE INDEX idx_personel_hesap_restoran ON public.personel_hesaplari USING btree (restaurant_id, durum);
CREATE UNIQUE INDEX uq_personel_hesap_rol ON public.personel_hesaplari USING btree (user_id, restaurant_id, rol) WHERE (test_hesabi = false);
CREATE UNIQUE INDEX uq_posta_masasi ON public.posta_masalari USING btree (table_id);
CREATE INDEX posta_personelleri_personel_idx ON public.posta_personelleri USING btree (personel_id);
CREATE INDEX idx_postalar_restoran ON public.postalar USING btree (restaurant_id);
CREATE INDEX idx_reservation_tables_reservation ON public.reservation_tables USING btree (reservation_id);
CREATE INDEX idx_reservation_tables_table ON public.reservation_tables USING btree (table_id);
CREATE INDEX idx_reservations_alan_hesap ON public.reservations USING btree (alan_hesap_id);
CREATE INDEX idx_reservations_anonymized ON public.reservations USING btree (anonymized_at);
CREATE INDEX idx_reservations_kisi_karti ON public.reservations USING btree (kisi_karti_id);
CREATE INDEX idx_reservations_reserved_at ON public.reservations USING btree (reserved_at);
CREATE INDEX idx_reservations_restaurant ON public.reservations USING btree (restaurant_id);
CREATE INDEX idx_rez_pr ON public.reservations USING btree (pr_id) WHERE (pr_id IS NOT NULL);
CREATE INDEX reservations_bekleme_idx ON public.reservations USING btree (restaurant_id, bekleme) WHERE (bekleme = true);
CREATE INDEX reservations_kisi_karti_tutar_idx ON public.reservations USING btree (kisi_karti_id) WHERE ((hesap_tutari IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX reservations_yedek_idx ON public.reservations USING btree (restaurant_id, yedek, reserved_at) WHERE (yedek AND (deleted_at IS NULL));
CREATE INDEX restaurant_photos_restaurant_idx ON public.restaurant_photos USING btree (restaurant_id, sira);
CREATE INDEX idx_restaurant_settings_restaurant ON public.restaurant_settings USING btree (restaurant_id);
CREATE INDEX idx_restaurant_tables_restaurant ON public.restaurant_tables USING btree (restaurant_id);
CREATE INDEX restaurant_tables_stok_idx ON public.restaurant_tables USING btree (restaurant_id, stok_gun) WHERE stok;
CREATE INDEX idx_restaurants_owner_user ON public.restaurants USING btree (owner_user_id);
CREATE UNIQUE INDEX uq_restoran_katilim_kodu ON public.restaurants USING btree (katilim_kodu) WHERE (katilim_kodu IS NOT NULL);
CREATE INDEX idx_rez_etiket_restoran ON public.rezervasyon_etiketleri USING btree (restaurant_id);
CREATE INDEX idx_salon_ogeleri_area ON public.salon_ogeleri USING btree (area_id);
CREATE INDEX idx_salon_ogeleri_restaurant ON public.salon_ogeleri USING btree (restaurant_id);
CREATE INDEX idx_staff_members_restaurant ON public.staff_members USING btree (restaurant_id);
